# tmux 3.x 設定。

source-file ~/.tmux/screen-keys.conf
source-file ~/.tmux/vim-keys.conf
source-file ~/.tmux/tmux.shared

set-option -g xterm-keys on
set-option -g default-terminal "tmux-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g set-titles on
set-option -g set-titles-string "#S:#I #W"
set-option -g history-limit 20000
set-option -g base-index 1
set-option -g renumber-windows on
set-option -g bell-action any
set-option -g display-panes-time 2000
set-option -g visual-bell on
set-option -g mouse on
set-option -s escape-time 0
set-window-option -g pane-base-index 1
set-window-option -g mode-keys vi
set-window-option -g automatic-rename on
set-window-option -g aggressive-resize on
setw -g clock-mode-colour green
setw -g clock-mode-style 24

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# 保持 SSH_AUTH_SOCK 等父層環境變數更新。
set-option -g update-environment "DISPLAY SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY"
